INSERT INTO projects (title, type, description, technologies, github_url, is_featured, is_visible, sort_order) VALUES
('Restaurant SaaS', 'Full Stack SaaS', 'Restoranların menü, masa, sipariş, mutfak ekranı ve ödeme süreçlerini yönetmesi için geliştirilen full-stack SaaS projesi. Express API, Prisma/PostgreSQL altyapısı, React arayüzü ve gerçek zamanlı sipariş akışıyla operasyon yönetimini dijitalleştirir.', 'React,TypeScript,Express,Prisma,PostgreSQL,Socket.IO', 'https://github.com/cemiltekin/restaurant-saas', 1, 1, 10),
('PromoCatch', 'Software Architecture', 'Kampanya ve fırsat takip sistemi olarak geliştirilen yazılım mimarisi projesi. Phase 1 ve Phase 2 teslimlerini tek repoda toplayarak SAD dokümanları, 4+1 mimari görünümleri, FastAPI backend, SQLite veri katmanı ve frontend demo ekranlarını içerir.', 'Python,FastAPI,SQLite,REST API,Docker,4+1 SAD', 'https://github.com/cemiltekin/promocatch', 1, 1, 20),
('YummyFast - Online Catering Service', 'Web & Backend', 'Online yemek/catering servisi için geliştirilmiş akademik bir yazılım mimarisi projesi. Sunum, kontrol, domain ve veri erişim katmanlarını ayırarak menü listeleme ve sipariş oluşturma gibi temel işlemleri daha sürdürülebilir bir backend yapısıyla ele alır.', 'Python,FastAPI,REST API,SQLite,Layered Architecture', 'https://github.com/cemiltekin/SOFT-ARCH-PROJECT', 1, 1, 30),
('Kişisel Portföy Web Sitesi', 'Web Tasarım', 'İş başvuruları ve profesyonel tanıtım için geliştirilen portföy web sitesi. Kişisel bilgiler, deneyim, eğitim, beceriler, projeler ve iletişim formunu tek sayfada erişilebilir ve responsive bir yapıda sunar.', 'HTML,CSS,JavaScript,Responsive Design', 'https://github.com/cemiltekin/WEB', 1, 1, 40),
('Software Security', 'Yazılım Güvenliği', 'Python ile yazılım güvenliği konularını çalışmak için oluşturulan akademik proje. Güvenli kodlama yaklaşımı, temel güvenlik kontrolleri ve yazılım geliştirme sürecinde risk farkındalığı üzerine odaklanır.', 'Python,Security,Secure Coding', 'https://github.com/cemiltekin/Software-Security', 1, 1, 50);

-- Create the first admin user after choosing a password:
-- INSERT INTO admin_users (username, password_hash)
-- VALUES ('admin', '$2y$10$REPLACE_WITH_PASSWORD_HASH');
